### ISSUE TITLE
Koodikatselmointi #2

### ISSUE THREAD

**Issue by impliedfeline** [JaakkoV/find-and-seek#1]
Ladattu 8.1.2017 klo 22:15

- Testit meni läpi, koodi kääntyi ja liikkuminen sekä liikkumisalgon vaihto toimi.
- Strategy pattern liikkumisalgon toteutuksessa kiva, enkapsuloi toiminnallisuuden siististi ja helposti muokattavaksi.
- Liikkumisalgon toteutuksessa käytettyjen tiettyjen näppäinpainallusten sijaan voisi käyttää liikkumissuuntia kuvaavia enumeraattoreita. (Direction.UP/Move.UP)

Erittäin siisti rakenne, koodi oli helppolukuista :)

**Comment by JaakkoV** [comment]
Kiitos kommentista ja havainnoista 👍
